#index:
#    path: /
#    controller: App\Controller\DefaultController::index

tasks_index:
   path: /tasks
   controller: App\Controller\TaskController::index  
   
task_edit:
   path: /tasks/edit/{id}
   controller: App\Controller\TaskController::edit  
   
task_delete:
   path: /tasks/delete/{id}
   controller: App\Controller\TaskController::delete     

task_detail:
   path: /task/show/{id}
   controller: App\Controller\TaskController::detail  

my_tasks:
   path: /mytasks
   controller: App\Controller\TaskController::MyTasks  

task_create:
   path: /task/create
   controller: App\Controller\TaskController::creation   


registro:
   path: /registro
   controller: App\Controller\UserController::register   

login:
   path: /login
   controller: App\Controller\UserController::login   

logout:
   path: /logout
   controller: App\Controller\UserController::logout  